### PR TITLE
Fixed new yaml deprecations

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR removes the deprecations introduces by the Symfony YAML component to be compatible with the YAML specification.

#### Why?

In some environment the tests were failing because of that.

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@danrot ACK

**Comment by danrot** [comment]
I am just waiting for @christianbader testing it out. Can be merged as soon as he approves the changes.

**Comment by danrot** [comment]
@wachterjohannes Was working on @christianbader's machine, but realized that we had two doctrine nodes in one config. Moved it, and wait for the tests again.

**Comment by danrot** [comment]
@wachterjohannes This can be merged now.

**Pull request merged**
