### PR TITLE
Added basic scaffolding template

### PR DESCRIPTION
**Pull request by wachterjohannes**
**default.xml**:

``` xml
    <view>ClientWebsiteBundle:Scaffolding:template</view>
    <controller>ClientWebsiteBundle:Scaffolding:index</controller>
```

**webspace.xml**:

``` xml
    <theme>
        <key>clean</key>
    </theme>
```

**Override single property <master.html.twig>:**

``` twig
{% block property_title %}
    <h2 property="{{ property.name }}">{{ content[property.name] }}</h2>
{% endblock %}
```

**Override single content-type <master.html.twig>:**

``` twig
{% block content_type_text_editor %}
    <h2 property="{{ property.name }}">{{ content[property.name] }}</h2>
{% endblock %}
```

**Beispiel:**
image

### CODE REVIEW

**Comment by danrot** [comment]
Is that still necessary? Assume that is solved by sulu-minimal in some way, isn't it?

**Comment by wachterjohannes** [comment]
Yes this should be forced someday (: but maybe in an own bundle. I sulu-minimal we only have a minimal template (with title and description nothing else). We should talk a out if we want to force something like this in sulu-namespace.

**Comment by danrot** [comment]
IMO that's a bit against our "We let you do whatever you want in the template"-philosophy. So if we do that i would move it into an own bundle. /cc @chirimoya

**Comment by wachterjohannes** [comment]
@danrot i think also we should move this to a optional bundle!

**Comment by danrot** [comment]
So we can close this one? Please reopen if you think otherwise.

**Pull request closed without merging**
