### PR TITLE
Fix compatibility with php 5.5

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| License | MIT

#### What's in this PR?

Allow symfony 2.8 and check if web server bundle exists.

#### Why?

Fix the compatibility with php 5.5 

#### Example Usage

~~~php
php55 /usr/local/bin/composer install
~~~

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Thanks to @ilyabakhlin who did add the last puzzle to make the test run on 5.5 again.

**Comment by danrot** [comment]
The build is failing for some reason different than before :see_no_evil: Can you investigate that? I'd say it should at least execute `composer install` correctly

**Comment by ilyabakhlin** [comment]
@alexander-schranz, the rebase has removed my changes, hahaha!

**Comment by alexander-schranz** [comment]
@ilyabakhlin ups fixed it xD

**Pull request merged**
