### PR TITLE
Update sulu.en.json

### PR DESCRIPTION
**Pull request by krewetka**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | 
| Related issues/PRs | 
| License | MIT
| Documentation PR | 

#### What's in this PR?

Just small hotfix - removing unnecesary word "anzeigen" from English translation for string public.show-selected.

#### Why?

Word shouldn't be there :)

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@krewetka thanks for your contribution. The removed value is used by sulu why do you want to remove it?

**Comment by krewetka** [comment]
I don't want to remove the value. Just English translation has extra German word in it:)

I just removed unnecesarry word "anzeigen" from English translation - nothing more.

image

**Comment by wachterjohannes** [comment]
ah ok now i have seen it. we manage our dependencies in xlf files of the bundles.you can find them in the filter `Resource/translations/sulu` after that we build the json files with the command `app/console sulu:build translations`. i have done this in this commit https://github.com/sulu/sulu-standard/commit/e7492cd31456d14607727d1c6ab3d10945d12a4d

**Comment by krewetka** [comment]
Ok, I see the commit https://github.com/sulu/sulu/commit/607dc180016e7b04edd8340740da3ec281b3dbb4

Thanks for explanation and quick change.

**Pull request closed without merging**
